wdinstagram_app/config/routes.rb
Rails.application.routes.draw do
  
  root "entries#index"
  
  resources :entries
  
end

wdinstagram_app/app/models/entry.rb
class Entry < ActiveRecord::Base
	validates :author, :photo_url, presence: true
end

wdinstagram_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wdinstagram_app/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :set_entry, only: [:show, :edit, :update, :destroy]

	def index
  	@entries = Entry.all
  end

  def show

  end

  def edit

  end

  def new
  	@entries = Entry.new
  end

  def create
  	@entry = Entry.new(entry_params)
  	if @entry.save
  		redirect_to entry_path(@entry)
  	else
  		render :new
  	end
  	
  end

  def update
  	@entry.update(entry_params)
  	if @entry.save
  		redirect_to entry_path(@entry)
  	else
  		render :edit
  	end
  end

  def destroy
  	@entry.destroy
  	redirect_to entries_path 
  end

  private

  def entry_params
  	params.require(:entry).permit(:author, :photo_url, :date_taken, :caption)
  end

  def set_entry
  	@entry = Entry.find(params[:id])
  end

end

wdinstagram_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wdinstagram_app/app/views/entries/_edit.html.erb
<%= form_for @entry do |e| %>
	<%= e.label :author %>
	<%= e.text_field :author %>
	<%= e.label :photo_url %>
	<%= e.text_field :photo_url %>
	<%= e.label :caption %>
	<%= e.text_field :caption %>
	<%= e.label :date_taken %>
	<%= e.text_field :date_taken %>
	<%= e.submit %>
<% end %>

wdinstagram_app/app/views/entries/_form.html.erb
<%= form_for @entries do |e| %>
	<%= e.label :author %>
	<%= e.text_field :author %>
	<%= e.label :photo_url %>
	<%= e.text_field :photo_url %>
	<%= e.label :caption %>
	<%= e.text_field :caption %>
	<%= e.label :date_taken %>
	<%= e.text_field :date_taken %>
	<%= e.submit %>
<% end %>

wdinstagram_app/app/views/entries/edit.html.erb
<h2 class="title">Edit this entry</h2>
<div class="form">
<%= render 'edit' %>
</div>
<%= link_to "Back", entries_path %>

wdinstagram_app/app/views/entries/index.html.erb
<h2><%= link_to 'New Entry', new_entry_path %></h2>
<h2 class="title">Entries</h2>
<div class="container">
	<% @entries.each do |entry| %>
	<div class="content">
		<h3>Author: <%= entry.author %></h3>
		<img src="<%= entry.photo_url %>">
		<p>Caption: <%= entry.caption %></p>
		<p>Date Taken: <%= entry.date_taken %></p>
		<%= link_to "Entry Page", entry_path(entry) %>
		<%= link_to "Edit Entry", edit_entry_path(entry) %>
		<%= link_to "Destroy Entry", entry_path(entry), method: :delete %>
	</div>
	<% end %>
</div>

wdinstagram_app/app/views/entries/new.html.erb
<h2 class="title">Create A New Entry Below</h2>
<div class="form">
  <%= render 'form' %>
</div>

wdinstagram_app/app/views/entries/show.html.erb
<h2 class="title">Entry</h2>
<div class="container">
	<h3>Author: <%= @entry.author %></h3>
	<img src="<%= @entry.photo_url %>"> 
	<p>Caption: <%= @entry.caption %></p>
	<p>Date Taken:<%= @entry.date_taken %></p>
	<%= link_to "Edit Entry", edit_entry_path(@entry)%>
	<%= link_to "Back", entries_path %>
</div>

wdinstagram_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdinstagramApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

	<h1>WDInstagram</h1>
<%= yield %>

</body>
</html>